# Generated by Django 3.2 on 2022-09-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220924_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='sprint',
        ),
        migrations.RemoveField(
            model_name='initiative',
            name='sprint',
        ),
        migrations.AddField(
            model_name='domain',
            name='sprints',
            field=models.ManyToManyField(to='app.Sprint'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='sprints',
            field=models.ManyToManyField(to='app.Sprint'),
        ),
    ]
