# Generated by Django 3.2 on 2022-09-25 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_level_member_role_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='level',
        ),
        migrations.AddField(
            model_name='member',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.level'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='member',
            name='role',
        ),
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.role'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='member',
            name='skill',
        ),
        migrations.AddField(
            model_name='member',
            name='skill',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.skill'),
            preserve_default=False,
        ),
    ]
