# Generated by Django 3.2 on 2022-09-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20220925_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='skill',
        ),
        migrations.AddField(
            model_name='member',
            name='skill',
            field=models.ManyToManyField(to='app.Skill'),
        ),
    ]
