# Generated by Django 3.2 on 2022-09-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20220925_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='manday_rate',
            field=models.DecimalField(decimal_places=2, default=30000000.0, max_digits=20, verbose_name='Manday Rate'),
        ),
    ]
