# Generated by Django 3.2 on 2022-09-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_squad_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='status',
            field=models.CharField(choices=[('0', 'Not Started'), ('1', 'Demand'), ('2', 'In Development'), ('3', 'Deployed')], default='0', max_length=2),
        ),
    ]
