# Generated by Django 3.2 on 2022-10-09 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_initiative_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='year',
            field=models.IntegerField(default=2022),
        ),
    ]
