# Generated by Django 3.2 on 2022-10-09 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_initiative_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initiative',
            name='year',
        ),
        migrations.AddField(
            model_name='sprint',
            name='year',
            field=models.IntegerField(default=2022),
        ),
    ]
