# Generated by Django 3.2 on 2022-10-09 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20221009_0417'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='order',
            field=models.IntegerField(default=0, max_length=2),
        ),
    ]
